package com.company.rumba.errors;

public enum ErrorType {
    ACCOUNT_NOT_CONFIRMED,
    CONFIRM_TOKEN_EXPIRED,
    CONFIRM_TOKEN_NOT_EXIST,
    EMAIL_CONFIRMED,
    EMAIL_EXIST,
    EMAIL_NOT_FOUND,
    EVENT_NOT_FOUND,
    FORBIDDEN,
    INVALID_CREDENTIALS,
    MEMBER_ALREADY_ASSIGNED,
    MEMBER_ALREADY_EXIST,
    MEMBER_NOT_FOUND,
    TASK_NOT_FOUND,
    VALIDATION_ERROR
}
